### ISSUE TITLE
There was something wrong in ./models/smpl.py    self.faces = data_struct.f    AttributeError: 'Struct' object has no attribute 'f'

### ISSUE THREAD

**Issue by 13136983989** [apple/ml-neuman#16]
Thanks for your excellent work!

Traceback (most recent call last):
  File "render_360.py", line 164, in <module>
    main_posed_360(opt)
  File "render_360.py", line 91, in main_posed_360
    smpl_type='optimized'
  File "/home/zhaozisong/ml-neuman/data_io/neuman_helper.py", line 245, in read_scene
    smpls, world_verts, static_verts, Ts = cls.read_smpls(scene_dir, scene.captures, scale=scale, smpl_type=smpl_type)
  File "/home/zhaozisong/ml-neuman/data_io/neuman_helper.py", line 272, in read_smpls
    device=device
  File "/home/zhaozisong/ml-neuman/models/smpl.py", line 76, in __init__
    self.faces = data_struct.f
AttributeError: 'Struct' object has no attribute 'f'

What should I do to solve this error so that I can start Render using pretrained model/Training the model?

**Comment by jiangwei221** [comment]
From the code at: https://github.com/apple/ml-neuman/blob/b5a9dae87e300a34412d18ced0ecafacc2cd6e07/models/smpl.py#L73-L76
, it seems that the SMPL pickle file is corrupted, or not the correct version.
