### ISSUE TITLE
WSL issue with Path to smpl_file

### ISSUE THREAD

**Issue by domattioli** [apple/ml-neuman#28]
No issues setting up the data directories nor environment, but I am having trouble getting any of the training rendering scripts to run thru my Ubuntu (20.04) WSL. Here's the error traceback resulting from the Train NeRF scene command, plus some debug print-outs:

```
(neuman_venv) domattioli@my_pc_wsl:~/Projects/HPSE/src/ml-neuman$ sudo env "PATH=$PATH" python train.py --scene_dir ./data/bike/ --name=bike_background --train_mode=bkg
[truncated output...]
Computing near/far for ['bkg']: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 104/104 [00:00<00:00, 438.03it/s]

-----Debug Print-Outs:-----
...creating 'smpl_path' var...
found this path: /home/domattioli/Projects/HPSE/src/ml-neuman/data/smplx/smpl/SMPL_NEUTRAL.pkl
....advancing to path check...
------------------------------

Traceback (most recent call last):
  File "train.py", line 262, in <module>
    train_background(opt)
  File "train.py", line 29, in train_background
    train_split, val_split, _ = neuman_helper.create_split_files(opt.scene_dir)
  File "/home/domattioli/Projects/HPSE/src/ml-neuman/data_io/neuman_helper.py", line 153, in create_split_files
    dummy_scene = NeuManReader.read_scene(scene_dir)
  File "/home/domattioli/Projects/HPSE/src/ml-neuman/data_io/neuman_helper.py", line 245, in read_scene
    smpls, world_verts, static_verts, Ts = cls.read_smpls(scene_dir, scene.captures, scale=scale, smpl_type=smpl_type)
  File "/home/domattioli/Projects/HPSE/src/ml-neuman/data_io/neuman_helper.py", line 272, in read_smpls
    device=device
  File "/home/domattioli/Projects/HPSE/src/ml-neuman/models/smpl.py", line 73, in __init__
    with open(smpl_path, 'rb') as smpl_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/domattioli/Projects/HPSE/src/ml-neuman/data/smplx/smpl/SMPL_NEUTRAL.pkl'
```

Yet, here is the path of the model and it appears to be located where it should:
```
(neuman_venv) domattioli@my_pc_wsl:~/Projects/HPSE/src/ml-neuman$ cd data/smplx/smpl
(neuman_venv) domattioli@my_pc_wsl:~/Projects/HPSE/src/ml-neuman/data/smplx/smpl$ ls
SMPL_NEUTRAL.pk1
```

I assume this is an issue associated with the WSL setup but I'd like a second set of eyes to double check that nothing in the repo is hard-coded.

**Comment by jiangwei221** [comment]
It looks like the file name is not .pkl, but .pk1(number 1, not L)

**Comment by domattioli** [comment]
Yikes. Thank you for your service; feel free to close.
