### ISSUE TITLE
Preprocess cannot optimize SMPL using silhouette for custom video

### ISSUE THREAD

**Issue by domattioli** [apple/ml-neuman#36]
I'm trying to train on a custom video but the `bash  -i ./run.sh` cannot get past the 10th steps:. The read out is:
```
alignment matrix saved at: /data/elements_of_dance-cut/output/alignments.npy
========================================
10/10: Optimize SMPL using silhouette
========================================
reading cameras: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30174.85it/s]
reading images meta: 100%|██████████████████████████████████████████████████████| 171/171 [00:00<00:00, 14839.26it/s]
reading point cloud: 100%|███████████████████████████████████████████████████| 6653/6653 [00:00<00:00, 212868.39it/s]
can not find keypoints for 00000.png
....
can not find keypoints for 00170.png
Computing near/far for ['bkg']: 100%|████████████████████████████████████████████| 171/171 [00:00<00:00, 1054.49it/s]
Traceback (most recent call last):
  File "optimize_smpl.py", line 327, in <module>
    main(opt)
  File "optimize_smpl.py", line 266, in main
    smpl_type='romp'
  File "../data_io/neuman_helper.py", line 245, in read_scene
    smpls, world_verts, static_verts, Ts = cls.read_smpls(scene_dir, scene.captures, scale=scale, smpl_type=smpl_type)
  File "../data_io/neuman_helper.py", line 272, in read_smpls
    device=device
  File "../models/smpl.py", line 71, in __init__
    smpl_path)
AssertionError: Path /neuman/data/smplx/smpl does not exist!
```

I'm confused on why this error is being thrown when there are .npy and .png files of the SMPL mesh for the human in each image of the video at ./output/smpl_pred.

**Comment by jiangwei221** [comment]
It looks like you didn't mount the SMPL folder to the container?
