### ISSUE TITLE
AssertionError: wrong patch size

### ISSUE THREAD

**Issue by xiyichen** [apple/ml-neuman#63]
> Train epoch=0:   0%|                                | 0/1000000 [00:00<?, ?it/s]
Train epoch=0:   0%|                                | 0/1000000 [00:05<?, ?it/s]
Train:   0%|                                              | 0/1 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 264, in <module>
    train_human(opt)
  File "train.py", line 154, in train_human
    trainer.train()
  File "/cluster/scratch/xiychen/ml-neuman/trainers/human_nerf_trainer.py", line 193, in train
    self.train_epoch()
  File "/cluster/scratch/xiychen/ml-neuman/trainers/human_nerf_trainer.py", line 618, in train_epoch
    leave=True,
  File "/cluster/scratch/xiychen/miniconda3/envs/neuman_venv/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/cluster/scratch/xiychen/miniconda3/envs/neuman_venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/cluster/scratch/xiychen/miniconda3/envs/neuman_venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/cluster/scratch/xiychen/miniconda3/envs/neuman_venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/cluster/scratch/xiychen/miniconda3/envs/neuman_venv/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/cluster/scratch/xiychen/miniconda3/envs/neuman_venv/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/cluster/scratch/xiychen/miniconda3/envs/neuman_venv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/cluster/scratch/xiychen/miniconda3/envs/neuman_venv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/cluster/scratch/xiychen/ml-neuman/datasets/human_rays.py", line 169, in __getitem__
    assert temp[seed[0]:bound[0], seed[1]:bound[1]].shape == (PATCH_SIZE, PATCH_SIZE), 'wrong patch size'
AssertionError: wrong patch size

I got this error when training the human model on one of my custom videos. It happened after loading the near/far cache files. The training for the scene went well, and this didn't happen to my other videos. Any suggestions on what could go wrong?

**Comment by jiangwei221** [comment]
Could you print the seed/bound/temp.shape? I think the seed value probably is wrong.

**Comment by xiyichen** [comment]
@jiangwei221 Thank you for your quick reply, the shapes are (2,) (2,) (715, 1273, 3)
I was wondering if cap.mask should only have one channel?

**Comment by jiangwei221** [comment]
It's weird that the seed is not a 2D coordinate, while it should be: https://github.com/apple/ml-neuman/blob/0149d258b2afe6ef65c91557bba9f874675871e4/datasets/human_rays.py#L34
Can you also print the shape of the cap.mask?
cap.mask is 2D mask with one-channel and is binary: https://github.com/apple/ml-neuman/blob/0149d258b2afe6ef65c91557bba9f874675871e4/data_io/neuman_helper.py#L55-L65

**Comment by xiyichen** [comment]
I found that somehow cap.mask has 3 channels: (715, 1273, 3). Does the image reader guarantee it's read as grayscale? I extracted the first channel in the mask function and now it is working correctly

**Comment by xiyichen** [comment]
I checked imageio.imread and the masks are indeed read as one-channel, not sure how it becomes 3 channels when loaded into cap.mask

**Comment by jiangwei221** [comment]
hmmm, not sure why, maybe you can add one more assertion to make sure the number of channels is correct...
