### ISSUE TITLE
关于数据预处理

### ISSUE THREAD

**Issue by Spphire** [apple/ml-neuman#69]
我这边用去年12月份成功预处理过的视频在最近又预处理了一次，在第八步发现报错
我又试过很多视频，都无法成功预处理
有无可能是gen_run.py里拉取的库最近有所更新而导致的不兼容？

**Comment by jiangwei221** [comment]
能不能给一下完整的报错

**Comment by Spphire** [comment]
> 能不能给一下完整的报错

         processing patch 72 | [  0 192 170 170]
         processing patch 73 | [  0 256 170 170]
         processing patch 74 | [  0 319 170 170]
         processing patch 75 | [  0 383 170 170]
         processing patch 76 | [  0 447 170 170]
finished
========================================
8/10: SMPL parameters
========================================
--2023-02-04 16:55:12--  https://github.com/jiangwei221/ROMP/releases/download/v1.1/model_data.zip
Resolving github.com (github.com)... ::ffff:20.205.243.166, 20.205.243.166
Connecting to github.com (github.com)|::ffff:20.205.243.166|:443... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-04 16:55:35--  (try: 2)  https://github.com/jiangwei221/ROMP/releases/download/v1.1/model_data.zip
Connecting to github.com (github.com)|::ffff:20.205.243.166|:443... failed: Connection refused.
Connecting to github.com (github.com)|20.205.243.166|:443... failed: Connection refused.
Resolving github.com (github.com)... ::ffff:20.205.243.166, 20.205.243.166
Connecting to github.com (github.com)|::ffff:20.205.243.166|:443... failed: Connection refused.
Connecting to github.com (github.com)|20.205.243.166|:443... failed: Connection refused.
unzip:  cannot find or open model_data.zip, model_data.zip.zip or model_data.zip.ZIP.
--2023-02-04 16:56:59--  https://github.com/Arthur151/ROMP/releases/download/v1.1/trained_models_try.zip
Resolving github.com (github.com)... 20.205.243.166, ::ffff:20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... failed: Connection refused.
Connecting to github.com (github.com)|::ffff:20.205.243.166|:443... failed: Connection refused.
unzip:  cannot find or open trained_models_try.zip, trained_models_try.zip.zip or trained_models_try.zip.ZIP.
No configs_yml is set, set it to the default --configs_yml=configs/image.yml
yaml_timestamp  /neuman/preprocess/ROMP/active_configs/active_context_2023-02-04_16_57_42.yaml
Loading the configurations from configs/image.yml
INFO:root:{'tab': 'hrnet_cm64_process_images', 'configs_yml': 'configs/image.yml', 'inputs': '/data/GENSHIN-CLIP/output/images', 'output_dir': '/data/GENSHIN-CLIP/output/smpl_pred', 'interactive_vis': False, 'show_largest_person_only': False, 'show_mesh_stand_on_image': False, 'soi_camera': 'far', 'make_tracking': False, 'temporal_optimization': False, 'save_dict_results': True, 'save_visualization_on_img': True, 'fps_save': 24, 'character': 'smpl', 'renderer': 'pytorch3d', 'f': None, 'model_return_loss': False, 'model_version': 1, 'multi_person': True, 'new_training': False, 'perspective_proj': False, 'FOV': 60, 'focal_length': 443.4, 'lr': 0.0003, 'adjust_lr_factor': 0.1, 'weight_decay': 1e-06, 'epoch': 120, 'fine_tune': True, 'GPUS': 0, 'batch_size': 64, 'input_size': 512, 'master_batch_size': -1, 'nw': 4, 'optimizer_type': 'Adam', 'pretrain': 'simplebaseline', 'fix_backbone_training_scratch': False, 'backbone': 'hrnet', 'model_precision': 'fp32', 'deconv_num': 0, 'head_block_num': 2, 'merge_smpl_camera_head': False, 'use_coordmaps': True, 'hrnet_pretrain': '/neuman/preprocess/ROMP/trained_models/pretrain_hrnet.pkl', 'resnet_pretrain': '/neuman/preprocess/ROMP/trained_models/pretrain_resnet.pkl', 'loss_thresh': 1000, 'max_supervise_num': -1, 'supervise_cam_params': False, 'match_preds_to_gts_for_supervision': False, 'matching_mode': 'all', 'supervise_global_rot': False, 'HMloss_type': 'MSE', 'eval': False, 'eval_datasets': 'pw3d', 'val_batch_size': 4, 'test_interval': 2000, 'fast_eval_iter': -1, 'top_n_error_vis': 6, 'eval_2dpose': False, 'calc_pck': False, 'PCK_thresh': 150, 'calc_PVE_error': False, 'centermap_size': 64, 'centermap_conf_thresh': 0.25, 'collision_aware_centermap': False, 'collision_factor': 0.2, 'center_def_kp': True, 'local_rank': 0, 'distributed_training': False, 'distillation_learning': False, 'teacher_model_path': '/export/home/suny/CenterMesh/trained_models/3dpw_88_57.8.pkl', 'print_freq': 50, 'model_path': 'trained_models/ROMP_HRNet32_V1.pkl', 'log_path': '/neuman/preprocess/log/', 'learn_2dpose': False, 'learn_AE': False, 'learn_kp2doffset': False, 'shuffle_crop_mode': False, 'shuffle_crop_ratio_3d': 0.9, 'shuffle_crop_ratio_2d': 0.1, 'Synthetic_occlusion_ratio': 0, 'color_jittering_ratio': 0.2, 'rotate_prob': 0.2, 'dataset_rootdir': '/neuman/preprocess/dataset/', 'dataset': 'h36m,mpii,coco,aich,up,ochuman,lsp,movi', 'voc_dir': '/neuman/preprocess/dataset/VOCdevkit/VOC2012/', 'max_person': 64, 'homogenize_pose_space': False, 'use_eft': True, 'smpl_mesh_root_align': False, 'Rot_type': '6D', 'rot_dim': 6, 'cam_dim': 3, 'beta_dim': 10, 'smpl_joint_num': 22, 'smpl_model_path': '/neuman/preprocess/ROMP/model_data/parameters', 'smpl_J_reg_h37m_path': '/neuman/preprocess/ROMP/model_data/parameters/J_regressor_h36m.npy', 'smpl_J_reg_extra_path': '/neuman/preprocess/ROMP/model_data/parameters/J_regressor_extra.npy', 'smpl_uvmap': '/neuman/preprocess/ROMP/model_data/parameters/smpl_vt_ft.npz', 'wardrobe': '/neuman/preprocess/ROMP/model_data/wardrobe', 'mesh_cloth': 'ghostwhite', 'nvxia_model_path': '/neuman/preprocess/ROMP/model_data/characters/nvxia', 'track_memory_usage': False, 'adjust_lr_epoch': [], 'kernel_sizes': [5], 'collect_subdirs': False, 'save_mesh': True, 'save_centermap': False}
INFO:root:------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/ROMP/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/ROMP/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/neuman/preprocess/ROMP/romp/predict/image.py", line 79, in <module>
    main()
  File "/neuman/preprocess/ROMP/romp/predict/image.py", line 71, in main
    processor = Image_processor(args_set=args_set)
  File "/neuman/preprocess/ROMP/romp/predict/image.py", line 14, in __init__
    super(Image_processor, self).__init__(**kwargs)
  File "/neuman/preprocess/ROMP/romp/predict/base_predictor.py", line 11, in __init__
    super(Predictor, self).__init__(**kwargs)
  File "/neuman/preprocess/ROMP/romp/base.py", line 35, in __init__
    self.visualizer = Visualizer(resolution=(512,512), result_img_dir=self.result_img_dir, with_renderer=True)
  File "/neuman/preprocess/ROMP/romp/lib/models/../utils/../visualization/visualization.py", line 34, in __init__
    self.smpl_face = torch.from_numpy(pickle.load(open(os.path.join(args().smpl_model_path,'SMPL_NEUTRAL.pkl'),'rb'), \
FileNotFoundError: [Errno 2] No such file or directory: '/neuman/preprocess/ROMP/model_data/parameters/SMPL_NEUTRAL.pkl'
========================================
9/10: Solve scale ambiguity

**Comment by Spphire** [comment]
![$L2T(54QX@0TF~E~Z65F6)2](https://user-images.githubusercontent.com/56157591/216798697-1942c412-ab14-4011-9c7c-e21eb8e65937.png)


> 能不能给一下完整的报错

**Comment by Spphire** [comment]
> 能不能给一下完整的报错

![KTNJ)5HS5%NG)7)@81Y`CVU](https://user-images.githubusercontent.com/56157591/216798726-96f3132d-dcde-4e2f-8d07-6e67592c5a55.png)

**Comment by Spphire** [comment]
> > 能不能给一下完整的报错
> 
> ![KTNJ)5HS5%NG)7)@81Y`CVU](https://user-images.githubusercontent.com/56157591/216798726-96f3132d-dcde-4e2f-8d07-6e67592c5a55.png)

这是今天最新跑的，报错不太一样

**Comment by jiangwei221** [comment]
你GitHub上的asset没有下载成功啊，挂个VPN试试

**Comment by Spphire** [comment]
@jiangwei221 
![$L2T(54QX@0TF~E~Z65F6)2](https://user-images.githubusercontent.com/56157591/216799484-035a187e-7554-4fad-b973-63eb4f20963c.png)

**Comment by Spphire** [comment]
> 能不能给一下完整的报错

![E}KD{1 {2_FM2UL8(QTRO$C](https://user-images.githubusercontent.com/56157591/216814704-e7d505f4-55d1-4586-b129-e0ca3a4e12da.png)

**Comment by Lowenicte** [comment]
> > 能不能给一下完整的报错
> 
> ![E}KD{1 {2_FM2UL8(QTRO$C](https://user-images.githubusercontent.com/56157591/216814704-e7d505f4-55d1-4586-b129-e0ca3a4e12da.png)

我也遇到了一样的问题，请问找到原因了吗

**Comment by Spphire** [comment]
> > > 能不能给一下完整的报错
> > 
> > 
> > ![E}KD{1 {2_FM2UL8(QTRO$C](https://user-images.githubusercontent.com/56157591/216814704-e7d505f4-55d1-4586-b129-e0ca3a4e12da.png)
> 
> 我也遇到了一样的问题，请问找到原因了吗

暂时没找到，你视频的相机运镜大致是咋样的？

**Comment by Lowenicte** [comment]
> > > > 能不能给一下完整的报错
> > > 
> > > 
> > > 
> > 
> > 
> > 我也遇到了一样的问题，请问找到原因了吗
> 
> 暂时没找到，你视频的相机运镜大致是咋样的？
在走廊里，前后走动、左右摆动两种吧

**Comment by Spphire** [comment]
新的报错
![LCCZWPS4EQ%N6JGVH6YULPP](https://user-images.githubusercontent.com/56157591/218095614-3385f003-3818-4b4a-a2c5-29ac7edb80f0.png)

**Comment by bryant-bai** [comment]
> 我这边用去年12月份成功预处理过的视频在最近又预处理了一次，在第八步发现报错 我又试过很多视频，都无法成功预处理 有无可能是gen_run.py里拉取的库最近有所更新而导致的不兼容？
你好，我也想运行一下这个代码，可以问些问题交流一下吗

**Comment by Spphire** [comment]
> > 我这边用去年12月份成功预处理过的视频在最近又预处理了一次，在第八步发现报错 我又试过很多视频，都无法成功预处理 有无可能是gen_run.py里拉取的库最近有所更新而导致的不兼容？
> > 你好，我也想运行一下这个代码，可以问些问题交流一下吗

可以的

**Comment by MikeAiJF** [comment]
> 能不能给一下完整的报错

你好，我想训练ml-hugs但是那个数据集是基于neuman的但是我现在处理自己的数据无法得到4d-huamns文件下的数据，请问你有好的方法吗，谢谢。

**Comment by GUI0809** [comment]
> > 能不能给一下完整的报错
> 
> 你好，我想训练ml-hugs但是那个数据集是基于neuman的但是我现在处理自己的数据无法得到4d-huamns文件下的数据，请问你有好的方法吗，谢谢。

你好，请问你找到好的解决方法了吗
