### ISSUE TITLE
"Error: Cannot Handle Data Type: (1, 1, 3), <f4"

### ISSUE THREAD

**Issue by mithunparab** [apple/ml-neuman#79]
```python
python render_360.py --scene_dir ./data/bike --weights_path ./out/bike_human/checkpoint.pth.tar --mode canonical_360
```
```
Traceback (most recent call last):
  File "/home/dtfrezer/miniconda3/envs/neuman_env/lib/python3.7/site-packages/PIL/Image.py", line 3089, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 3), '<f4')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "render_360.py", line 162, in <module>
    main_canonical_360(opt)
  File "render_360.py", line 80, in main_canonical_360
    imageio.imsave(save_path, out)
  File "/home/dtfrezer/miniconda3/envs/neuman_env/lib/python3.7/site-packages/imageio/v2.py", line 386, in imwrite
    return file.write(im, **kwargs)
  File "/home/dtfrezer/miniconda3/envs/neuman_env/lib/python3.7/site-packages/imageio/plugins/pillow.py", line 387, in write
    pil_frame = Image.fromarray(frame, mode=mode)
  File "/home/dtfrezer/miniconda3/envs/neuman_env/lib/python3.7/site-packages/PIL/Image.py", line 3092, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 3), <f4
````

**Comment by mithunparab** [comment]
Fix #80
